### ISSUE TITLE
Doesn't work in Docker for Windows

### ISSUE THREAD

**Issue by mjonescase** [Ekito/docker-cron#3]
I cloned this repo on my Mac and it worked great. But when I tried it on my Windows 10 laptop running Docker and configured to use Linux containers, nothing ever showed up in /var/log/cron.log.

I'll continue to troubleshoot and update this issue with anything I learn.

**Comment by Thibdx** [comment]
Are you in a Linux shell ? Cron is not on Windows.

**Comment by stanstrup** [comment]
I am having the same issue. Windows host. I tried all the examples on stackoverflow and nothing is ever written to the log or directly in the shell (for the examples that attempt that).
it is like cron is not doing anything.

EDIT: I confirmed that in an VM ubuntu host this works as it should. So it indeed seems to be a windows issue.
EDIT2: Asked here https://stackoverflow.com/questions/56341584/running-cron-in-a-docker-container-on-a-windows-host

**Comment by rferrali** [comment]
Had the same issue. Fixed it by changing line ending of the crontab file from CRLF to LF. Hope this helps!

**Comment by jbernier** [comment]
> Had the same issue. Fixed it by changing line ending of the crontab file from CRLF to LF. Hope this helps!

I know this is an old thread but just wanted to say that this saved me after 3 days of searching and testing.

You nailed it !

**Comment by mjonescase** [comment]
Closing, looks like it's a solved problem.
